const officeHolders = {
  // 54: 'Betty T. Ferguson',
  // 55: 'James Burke',
  // 56: 'Arthur E. Teele, Jr.',
  // 57: 'Gwen Margolis',
  // 58: 'Bruce C. Kaplan',
  // 59: 'Pedro Reboredo',
  60: 'Maurice A. Ferre',
  61: 'Katy Sorenson',
  62: 'Dennis C. Moss',
  64: 'Miguel Diaz de la Portilla',
  65: 'Alexander Penelas',
  249: 'Dr. Miriam Alonso',
  251: 'Jimmy L. Morales',
  352: 'Bruno A. Barreiro',
  427: 'Natacha Seijas',
  431: 'Joe A. Martinez',
  455: 'Rebeca Sosa',
  476: 'Dr. Barbara Carey-Shuler',
  486: 'Sen. Javier D. Souto',
  495: 'Jose "Pepe" Cancio, Sr.',
  505: 'Jose "Pepe" Diaz',
  506: 'Sally A. Heyman',
  507: 'Dorrin  Rolle',
  554: 'Carlos A. Gimenez',
  555: 'Barbara J. Jordan',
  571: 'Audrey M. Edmonson',
  625: 'Lynda Bell',
  626: 'Jean Monestime',
  641: 'Esteban L. Bovo, Jr.',
  642: 'Xavier L. Suarez',
  663: 'Juan C. Zapata',
  676: 'Daniella Levine Cava',
  699: 'Eileen Higgins'
}

module.exports = officeHolders
